version: "3.9"
services:
  redpanda:
    image: redpandadata/redpanda:latest
    command: >
      redpanda start --overprovisioned --smp 1 --memory 1G --reserve-memory 0M
      --node-id 0 --check=false
      --kafka-addr 0.0.0.0:9092
      --advertise-kafka-addr localhost:9092
    ports:
      - "9092:9092"
      - "9644:9644"
